package move;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-16T14:24:37.047-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://move/", name = "MoveInvestment")
@XmlSeeAlso({ObjectFactory.class})
public interface MoveInvestment {

    @WebMethod
    @RequestWrapper(localName = "investmentValue", targetNamespace = "http://move/", className = "move.InvestmentValue")
    @ResponseWrapper(localName = "investmentValueResponse", targetNamespace = "http://move/", className = "move.InvestmentValueResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String investmentValue(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getQuote", targetNamespace = "http://move/", className = "move.GetQuote")
    @ResponseWrapper(localName = "getQuoteResponse", targetNamespace = "http://move/", className = "move.GetQuoteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Double getQuote(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
